name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Build 
      run: cargo build

    - name: Run tests
      run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure rust
      run: |
        rustup component add clippy
      
    - name: Clippy
      run: RUSTFLAGS="-Dwarnings" cargo clippy

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure rust
      run: |
        rustup component add rustfmt

    - name: Fmt
      run: cargo fmt -- --check
